HEAD
name: CI Ecosoft

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build --if-present

      - name: Run tests
        run: npm test --if-present

      - name: Run lint
        run: npm run lint --if-present
=======
name: CI Ecosoft

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependencias backend
        run: |
          cd backend
          npm install

      - name: Instalar dependencias frontend
        run: |
          cd frontend
          npm install

      - name: Compilar frontend
        run: |
          cd frontend
          npm run build

      - name: Linter backend
        run: |
          cd backend
          npm run lint || echo "No hay lint configurado"

      - name: Linter frontend
        run: |
          cd frontend
          npm run lint || echo "No hay lint configurado"

      - name: Tests backend
        run: |
          cd backend
          npm test || echo "No hay tests configurados"

      - name: Tests frontend
        run: |
          cd frontend
          npm test || echo "No hay tests configurados"

